LANGUAGES_KEYWORDS = {
  :vb => {:keyword => ['me', 'addhandler', 'addressof', 'alias', 'andalso', 'byref', 'byte', 'byVal', 'case', 'catch', 'cbool', 'cbyte', 'cchar', 'cdate', 'cdec', 'cdbl', 'char', 'cint', 'clng', 'cobj', 'const', 'continue', 'csbyte', 'cshort', 'csng', 'cstr', 'ctype', 'cuint', 'culng', 'cushort', 'declare', 'delegate', 'directcast', 'each', 'else', 'elseif', 'endif', 'enum', 'erase', 'finally', 'for', 'friend', 'function', 'gettype', 'getxmlnamespace', 'global', 'gosub', 'goto', 'handles', 'if', 'implements', 'imports', 'inherits', 'integer', 'interface', 'isnot', 'loop', 'mod', 'module', 'mustinherit', 'mustoverride', 'mybase', 'myclass', 'namespace', 'narrowing', 'nothing', 'notinheritable', 'notoverridable', 'object','operator', 'option', 'optional', 'orelse', 'overloads', 'overridable', 'overrides', 'paramarray', 'partial', 'property', 'raiseevent', 'readonly', 'redim', 'rem', 'removehandler', 'resume', 'sbyte', 'shadows', 'shared', 'short', 'single', 'step', 'stop', 'structure', 'sub', 'synclock', 'throw', 'try', 'trycast', 'Variant', 'wend', 'ushort', 'when', 'while', 'widening', 'withevents', 'writeonly', 'NameValueCollection', '^End Sub'], :extension => ['.vb']},
  :csharp => { :keyword => ['me', '^var', 'abstract', 'base', 'break', 'case', 'catch', 'char', 'checked', 'const', 'continue', 'decimal', 'default', 'delegate', 'double', 'else', 'enum', 'explicit', 'extern', 'finally', 'fixed', 'float', 'for', 'foreach', 'goto', 'if', 'implicit', 'interface', 'internal', 'namespace', 'object', 'operator', 'override', 'readonly', 'ref', 'sbyte', 'sealed', 'short', 'sizeof', 'stackalloc', 'struct', 'switch', 'throw', 'try', 'typeof', 'uint', 'ulong', 'unchecked', 'unsafe', 'ushort', 'using', 'virtual', 'volatile', 'while', 'NameValueCollection','\.ToInt32', 'void'], :extension => ['.cs']},
  :c => { :keyword => ['auto', '_Bool', 'break', 'case', 'char', '_Complex', 'const', 'continue', 'default', 'do', 'double', 'else', 'enum', 'extern', 'float', 'for', 'goto', 'if', '_Imaginary', 'inline', 'register', 'restrict', 'short', 'signed', 'sizeof', 'struct', 'switch', 'typedef', 'union', 'unsigned', 'void', 'volatile', 'while', '\#if', '\#include', '\#else', '\#endif', '\#elif'], :extension => ['.c', '.h'] },
  :cpp => { :keyword => ['alignas', 'alignof', 'and_eq', 'asm', 'auto', 'bitand', 'bitor', 'break', 'case', 'catch', 'char', 'char16_t', 'char32_t', 'compl', 'const', 'constexpr', 'const_cast', 'continue', 'decltype', 'default', 'do', 'double', 'dynamic_cast', 'else', 'enum', 'explicit', 'export', 'extern', 'float', 'for', 'friend', 'goto', 'if', 'inline', 'mutable', 'namespace', 'noexcept', 'not_eq', 'nullptr', 'operator', 'or_eq', 'register', 'reinterpret_cast', 'short', 'signed', 'sizeof', 'static_assert', 'static_cast', 'struct', 'switch', 'template ', 'thread_local', 'throw', 'try', 'typedef', 'typeid', 'typename', 'union', 'unsigned', 'virtual', 'volatile', 'wchar_t', 'while', 'xor', 'xor_eq', 'override', 'final', '\#if', '\#include', '\#else', '\#endif', '\#elif'], :extension => ['.cpp', '.h'] },
  :java => { :keyword => ['abstract', 'continue', 'for', 'switch', 'assert', 'default', 'if', 'package', 'synchronized', 'do', 'goto', 'break', 'double', 'implements', 'throw', 'byte', 'else', 'import', 'throws', 'case', 'enum', 'instanceof', 'transient', 'catch', 'extends', 'try', 'char', 'final', 'interface', 'finally', 'strictfp', 'volatile', 'const', 'float', 'native', 'super', 'while'], :extension => ['.java'] },
  :ruby => { :keyword => ['__FILE__', 'def', 'unless', '__LINE__', 'begin', 'defined\?', 'ensure', 'module', 'redo', 'super', 'until', 'BEGIN', 'break', 'do', 'rescue', 'then', 'when', 'case', 'else', 'for', 'nil', 'retry', 'while', 'alias', 'elsif', 'if', 'undef', 'yield', 'require', 'end$'], :extension => ['.rb'] },
  :python => { :keyword => ['as', 'assert', 'break', 'continue', 'def', 'else', 'except', 'exec', 'finally', 'for', 'global', 'if', 'import', 'lambda', 'None', 'nonlocal', 'pass', 'raise', 'try', 'while', 'yield', '^from', '__future__', '__module__', '__name__'], :extension => ['.py'] },
  :php => { :keyword => ['implode', 'explode', 'htmlspecialchars', 'mysql_query', '__halt_compiler', 'as', 'break', 'callable', 'case', 'catch', 'clone', 'const', 'continue', 'declare', 'default', 'die', 'do', 'echo', 'else', 'elseif', 'enddeclare', 'endfor', 'endforeach', 'endif', 'endswitch', 'endwhile', 'eval', 'extends', 'final', 'for', 'foreach', 'function', 'global', 'goto', 'if', 'implements', '^include', 'include_once', 'instanceof', 'insteadof', 'namespace', '^require', '^require_once', 'switch', 'throw', 'trait', 'try', 'unset', '^use', 'while', '<\?php', '<\?', '\?>', 'then', 'when'], :extension => ['.php'] }
}

UNIQUE_KEYWORD_WEIGHT = 4
KEYWORD_WEIGHT = 1
EXTENSION_WEIGHT = 30
